### PR TITLE
Update: Add monitor_url to verflier messages

### PR DESCRIPTION
**Pull request by chrisbliss18**
The verifliers code was not fully updated to handle sending the `monitor_url` along with the `blog_id`. This means that the verifliers could not accurately report which site they were reporting results for. This PR is a partial fix for this issue. This fix focuses on ensuring that the `monitor_url` is passed through the messaging sent back to Jetmon.

A big issue remains however: the retry queue tracks sites to retry by just the `blog_id`. This means that the retry queue is ambiguous. The entire retry queue system (including in the verifliers) must be updated to a system that either utilizes the `jetpack_monitor_site_id` for unique site IDs or to somehow combine the `blog_id` and `monitor_id`. I believe that the first option, using `jetpack_monitor_site_id`, is a more simple approach, but everything in Jetmon, the workers, and the verifliers will all need to be updated to use this approach. If this approach is used, this PR is not necessary as the new ID will be sufficient to track both the `blog_id` and `monitor_url`.

## Testing Instruction

1. Checkout the latest `master` branch.
2. Add a `console.log` or similar debug output to the top of the `checkHostStatus` function in `lib/jetmon.js`, such as: `console.log({data: data});`
3. Run Jetmon and have at least one test site change its status.
4. Confirm that the debug output shows that the `data` object does not have an entry for `monitor_url`.
5. Checkout out this PR's branch (`update/add-monitor_url-to-veriflier-messages`).
6. Rebuild the project: `sudo docker compose build --no-cache`
7. Ensure that the same debug output code as you added in step 2 is present.
8. Run Jetmon and have at least one test site change its status.
9. Confirm that the debug output shows that the `data` object now has an entry for `monitor_url`.

### CODE REVIEW

**Comment by fgiannar** [comment]
If my understanding is correct, with the current changes you are introducing the only additional change needed to fix the retry queue logic would be replacing `if ( queuedRetries[ loop ].blog_id != data.blog_id ) {` in [jetmon.js](https://github.com/Automattic/jetmon/blob/master/lib/jetmon.js#L289) with something like `if ( queuedRetries[ loop ].blog_id != data.blog_id || queuedRetries[ loop ]. monitor_url != data. monitor_url) {`, right?

**Comment by chrisbliss18** [comment]
> If my understanding is correct, with the current changes you are introducing the only additional change needed to fix the retry queue logic would be replacing `if ( queuedRetries[ loop ].blog_id != data.blog_id ) {` in [jetmon.js](https://github.com/Automattic/jetmon/blob/master/lib/jetmon.js#L289) with something like `if ( queuedRetries[ loop ].blog_id != data.blog_id || queuedRetries[ loop ]. monitor_url != data.monitor_url) {`, right?

@fgiannar Correct. This way it won't retry with the data for another monitored URL with the same blog ID.

**Comment by fgiannar** [comment]
> If you think it's appropriate, I can add that change to this PR. Thoughts?

I think it makes sense, yes!

**Comment by fgiannar** [comment]
Thanks for working on this, Chris!

I noticed that the current veriflier logic for adding checks involves only checking the `blog_id` [here](https://github.com/Automattic/jetmon/blob/master/veriflier/source/check_controller.cpp#L125).

Assuming two different URLs being monitored for the same blog, this would result in the corresponding check for the second url not to happen.

We might also need to update the logic [here](https://github.com/Automattic/jetmon/blob/master/veriflier/source/check_controller.cpp#L51) when a check is finished.

Not sure if you are aware of these issues or planning to address them in a follow up PR :)

**Review by fgiannar — APPROVED** [review]
Awesome, Chris! Many thanks for working on this and incorporating the suggested changes! Let's 🚢 !

**Pull request merged**
